version: '3'

services:
  app:
    build: .
    container_name: server-monitor
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/serverguard
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - CLIENT_URL=${CLIENT_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - MONITORING_INTERVAL=${MONITORING_INTERVAL}
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data: